name: Build and Push Docker Image to AWS ECR

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.IAM_KOLKN }}
          aws-secret-access-key: ${{ secrets.PASS_KOLKN }}
          aws-region: ${{ secrets.REGION }}

      - name: Login to Amazon ECR
        env:
          AWS_REGION: ${{ secrets.REGION }}
          AWS_REPO_URI: ${{ secrets.KOLKN_URI }}
        run: |
          aws ecr get-login-password --region ${{ secrets.REGION }} | docker login --username AWS --password-stdin $AWS_REPO_URI

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.KOLKN_REPO }}:latest .

      - name: Tag Docker image for ECR
        env:
          AWS_REPO_URI: ${{ secrets.KOLKN_URI }}
        run: |
          docker tag ${{ secrets.KOLKN_REPO }}:latest $AWS_REPO_URI/${{ secrets.KOLKN_REPO }}:latest

      - name: Push Docker image to ECR
        env:
          AWS_REPO_URI: ${{ secrets.KOLKN_URI }}
        run: |
          docker push $AWS_REPO_URI/${{ secrets.KOLKN_REPO }}:latest
